mod_id=simplebbq
mod_name=SimpleBBQ

major_version=1
minor_version=0
patch_version=3
version_label=release

minecraft_version=1.20.1
loader_version=0.16.14
fabric_version=0.92.5+1.20.1
parchment_mappings=2023.09.03

modmenu_version=7.2.2
forgeconfigapiport_version=v8.0.2-1.20.1-Fabric
jei_version=15.20.0.106

portinglib_version=2.3.8+1.20.1
portinglib_modules=core,transfer,data,model_generators,model_materials
reachentityattributes_version=2.4.0

# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
