modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory
license="MIT" #mandatory
issueTrackerURL="https://github.com/MCTeamPotato/SimpleBBQ-Unofficial/issues" #optional

[[mods]] #mandatory
modId="simplebbq" #mandatory
version="${version}" #mandatory
displayName="Simple BBQ Unofficial" #mandatory
displayURL="https://github.com/MCTeamPotato/SimpleBBQ-Unofficial/" #optional
logoFile="banner.png" #optional
authors="Si_hen, VVVHY, idyllicbean, SeraphJack, TeamPotato" #optional
description='''
Relaxing and Enjoyable Barbecue.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.simplebbq]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.simplebbq]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
